### ISSUE TITLE
Remove the two first spam comments on SO questions

### ISSUE THREAD

**Issue by Aralun** [SO-Close-Vote-Reviewers/auto-comments#23]
The [two first `Spam!!` comments](https://github.com/SO-Close-Vote-Reviewers/auto-comments/blob/master/sites/stackoverflow.com/questions.md) are somewhat outdated now, Charcoal and SOCVR and SOBotics regulars have become impressively efficient at taking down spam in record time.

Should they be expunged from the auto-comments?

**Comment by gunr2171** [comment]
+1 to removing them
