### ISSUE TITLE
Would a link to the "Why is 'please help me not a question?" be useful?

### ISSUE THREAD

**Issue by halfer** [SO-Close-Vote-Reviewers/auto-comments#25]
I don't have anything written yet, but would it be helpful to have some text in `stackoverflow.com/questions.md` for this Meta post?

[Why is “Can someone help me?” not an actual question?](https://meta.stackoverflow.com/questions/284236/why-is-can-someone-help-me-not-an-actual-question)

I find myself posting this one (and some related explanation) when something is too broad, and the OP believes that the magic phrase will implicitly ask all the necessary questions for them. It is somewhat related to a few existing phrases that are responses to essentially too broad or poorly defined problems.

What do folks think? I will write something out if people think it will be separately useful over the existing phrases.

**Comment by gunr2171** [comment]
Sorry for the delay. Answer is "yes".

**Comment by halfer** [comment]
Great. I've added a PR, feel free to suggest changes over there.
