### ISSUE TITLE
Establish an ordering for types of comments

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/auto-comments#26]
This ordering should be based on how frequently those comments are used. Maybe some SEDE data could be helpful (assuming comments are not used primarily for deleted posts).

For example: spam should be at the top.

Also, it would be nice if the Auto-Comments userscript could support categories.

**Comment by Aralun** [comment]
Wouldn't categories or ordering best be done inside the US rather than in our repos?

**Comment by gunr2171** [comment]
Yes, and it seems that that feature is already requested: https://github.com/Benjol/SE-AutoReviewComments/issues/121

**Comment by Aralun** [comment]
Precisely a year ago, even. I'll dig into this.

**Comment by gunr2171** [comment]
Might as well get around to looking at old issues...

So the autocomments userscript has a "filter" feature - essentially a search box. To me, this is a good replacement feature.
