### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by kevinmmansour** [SO-Close-Vote-Reviewers/auto-comments#60]
I think the list is very nice but we must add Auto-comment for Homework or assignments question;
Also Please review my issue do not disregard it beacauseit will save time.

**Comment by gunr2171** [comment]
There already is a homework auto comment for questions:

```
###[Q] Homework question without effort Questions asking for homework help must include a summary of the work you've done so far to solve the problem, and a description of the difficulty you are having solving it. Please read How to ask homework questions and [edit] your post.
```

Does this work for you. Are you looking for this in another category, or with a variation?

**Comment by kevinmmansour** [comment]
Thanks; I am didn't see it.
