### ISSUE TITLE
comments.socvr.org is down

### ISSUE THREAD

**Issue by MdoubleDash** [SO-Close-Vote-Reviewers/auto-comments#65]
It seems that https://comments.socvr.org/ is down. We can still use "https://socvr.org/comments/stackoverflow.com.jsonp" from SOCVR tools, but not sure what happened here. If there are no plans to restore this, then we should update the ReadMe file.

**Comment by gunr2171** [comment]
Sorry, I must have missed that one. Fixed with 2afada584dd2e5c7cc8ef3e3acefb8b042f405d0

**Comment by gunr2171** [comment]
For reference: https://github.com/SO-Close-Vote-Reviewers/socvr.org/issues/4
